import PrivateBluetoothSdkModule from "./_private/BluetoothSdkModule"
import type {
  BluetoothSdkEventListener,
  BluetoothSdkEventName,
  BluetoothSdkPublicModule,
  PublicBluetoothStatus,
  PublicGlassesStatus,
  VideoRecordingDefaults,
} from "./BluetoothSdk.types"
import {getReleaseChangelogs} from "./changelogs"

const PUBLIC_EVENT_NAMES = new Set<BluetoothSdkEventName>([
  "log",
  "device_discovered",
  "default_device_changed",
  "glasses_not_ready",
  "button_press",
  "touch_event",
  "accel_event",
  "head_up",
  "voice_activity_detection_status",
  "speaking_status",
  "battery_status",
  "local_transcription",
  "wifi_status_change",
  "wifi_scan_result",
  "hotspot_status_change",
  "hotspot_error",
  "photo_response",
  "photo_status",
  "camera_status",
  "video_recording_status",
  "media_success",
  "media_error",
  "gallery_status",
  "compatible_glasses_search_stop",
  "swipe_volume_status",
  "switch_status",
  "rgb_led_control_response",
  "settings_ack",
  "pair_failure",
  "pairing_info",
  "entering_pairing_mode",
  "owner_replaced",
  "audio_pairing_needed",
  "audio_connected",
  "audio_disconnected",
  "mic_pcm",
  "mic_lc3",
  "mic_health",
  "stream_status",
  "camera_preview_status",
  "mtk_update_complete",
  "glasses_session_changed",
  "ota_start_ack",
  "ota_status",
  "ar99_ota_status",
  "version_info",
  "extraction_progress",
])

const addListener: BluetoothSdkPublicModule["addListener"] = (eventName, listener) => {
  if (!PUBLIC_EVENT_NAMES.has(eventName)) {
    throw new Error(`Unsupported BluetoothSdk event "${eventName}". Use @mentra/bluetooth-sdk/react for status state.`)
  }
  return PrivateBluetoothSdkModule.addListener(eventName, listener as BluetoothSdkEventListener<BluetoothSdkEventName>)
}

const startOtaUpdate: BluetoothSdkPublicModule["startOtaUpdate"] = (otaVersionUrl) => {
  return PrivateBluetoothSdkModule.startOtaUpdate(otaVersionUrl)
}

const queryOtaStatus: BluetoothSdkPublicModule["queryOtaStatus"] = () => {
  return PrivateBluetoothSdkModule.sendOtaQueryStatus()
}

const bindPublicMethod = <K extends keyof BluetoothSdkPublicModule>(name: K): BluetoothSdkPublicModule[K] => {
  const method = (PrivateBluetoothSdkModule as unknown as Record<string, unknown>)[name]
  if (typeof method === "function") {
    return method.bind(PrivateBluetoothSdkModule) as BluetoothSdkPublicModule[K]
  }

  return (async () => {
    throw new Error(`BluetoothSdk.${String(name)} is not available in this native build. Rebuild the app.`)
  }) as unknown as BluetoothSdkPublicModule[K]
}

export const BluetoothSdk: BluetoothSdkPublicModule = Object.freeze({
  addListener,
  getGlassesStatus: bindPublicMethod("getGlassesStatus"),
  getBluetoothStatus: bindPublicMethod("getBluetoothStatus"),
  subscribeGlassesStatus: (listener: (changed: Partial<PublicGlassesStatus>) => void) =>
    PrivateBluetoothSdkModule.onGlassesStatus(listener),
  subscribeBluetoothStatus: (listener: (changed: Partial<PublicBluetoothStatus>) => void) =>
    PrivateBluetoothSdkModule.onBluetoothStatus(listener),
  getDefaultDevice: bindPublicMethod("getDefaultDevice"),
  setDefaultDevice: bindPublicMethod("setDefaultDevice"),
  clearDefaultDevice: bindPublicMethod("clearDefaultDevice"),
  startScan: bindPublicMethod("startScan"),
  stopScan: bindPublicMethod("stopScan"),
  scan: bindPublicMethod("scan") as BluetoothSdkPublicModule["scan"],
  connect: bindPublicMethod("connect"),
  connectDefault: bindPublicMethod("connectDefault"),
  cancelConnectionAttempt: bindPublicMethod("cancelConnectionAttempt"),
  disconnect: bindPublicMethod("disconnect"),
  forget: bindPublicMethod("forget"),
  displayText: bindPublicMethod("displayText"),
  clearDisplay: bindPublicMethod("clearDisplay"),
  showDashboard: bindPublicMethod("showDashboard"),
  setDashboardPosition: bindPublicMethod("setDashboardPosition"),
  setHeadUpAngle: bindPublicMethod("setHeadUpAngle"),
  setImuEnabled: bindPublicMethod("setImuEnabled"),
  setScreenDisabled: bindPublicMethod("setScreenDisabled"),
  ping: bindPublicMethod("ping"),
  requestWifiScan: bindPublicMethod("requestWifiScan"),
  sendWifiCredentials: bindPublicMethod("sendWifiCredentials"),
  forgetWifiNetwork: bindPublicMethod("forgetWifiNetwork"),
  setHotspotState: bindPublicMethod("setHotspotState"),
  setSystemTime: bindPublicMethod("setSystemTime"),
  setWifiAdbState: bindPublicMethod("setWifiAdbState"),
  setGalleryModeEnabled: bindPublicMethod("setGalleryModeEnabled"),
  setVoiceActivityDetectionEnabled: bindPublicMethod("setVoiceActivityDetectionEnabled"),
  setLoudnessGateEnabled: bindPublicMethod("setLoudnessGateEnabled"),
  /**
   * @deprecated Sticky action-button photo presets are deprecated. Prefer per-request
   * `requestPhoto(...)` options (e.g. `mode: "text"` for text sensor size/crop, or explicit per-shot
   * fields). Still functional until removed in a future release.
   */
  setPhotoCaptureDefaults: bindPublicMethod("setPhotoCaptureDefaults"),
  setVideoRecordingDefaults: ({width, height, fps}: VideoRecordingDefaults) => {
    const method = (PrivateBluetoothSdkModule as unknown as Record<string, unknown>).setVideoRecordingDefaults
    if (typeof method !== "function") {
      return Promise.reject(
        new Error("BluetoothSdk.setVideoRecordingDefaults is not available in this native build. Rebuild the app."),
      )
    }
    return PrivateBluetoothSdkModule.setVideoRecordingDefaults(width, height, fps)
  },
  setMaxVideoRecordingDuration: bindPublicMethod("setMaxVideoRecordingDuration"),
  setCameraFov: bindPublicMethod("setCameraFov"),
  setLegacyCameraFov: bindPublicMethod("setLegacyCameraFov"),
  setCameraFovOverride: bindPublicMethod("setCameraFovOverride"),
  releaseCameraFovOverride: bindPublicMethod("releaseCameraFovOverride"),
  setCameraTuningConfig: bindPublicMethod("setCameraTuningConfig"),
  queryGalleryStatus: bindPublicMethod("queryGalleryStatus"),
  requestPhoto: bindPublicMethod("requestPhoto"),
  warmUpCamera: bindPublicMethod("warmUpCamera"),
  stopCameraWarmUp: bindPublicMethod("stopCameraWarmUp"),
  startVideoRecording: bindPublicMethod("startVideoRecording"),
  stopVideoRecording: bindPublicMethod("stopVideoRecording"),
  queryVideoRecordingStatus: bindPublicMethod("queryVideoRecordingStatus"),
  startStream: bindPublicMethod("startStream"),
  stopStream: bindPublicMethod("stopStream"),
  startCameraPreview: bindPublicMethod("startCameraPreview"),
  stopCameraPreview: bindPublicMethod("stopCameraPreview"),
  setMicState: bindPublicMethod("setMicState"),
  setPreferredMic: bindPublicMethod("setPreferredMic"),
  setOwnAppAudioPlaying: bindPublicMethod("setOwnAppAudioPlaying"),
  getGlassesMediaVolume: bindPublicMethod("getGlassesMediaVolume"),
  setGlassesMediaVolume: bindPublicMethod("setGlassesMediaVolume"),
  rgbLedControl: bindPublicMethod("rgbLedControl"),
  requestVersionInfo: bindPublicMethod("requestVersionInfo"),
  setOtaVersionUrl: bindPublicMethod("setOtaVersionUrl"),
  getOtaVersionUrl: bindPublicMethod("getOtaVersionUrl"),
  checkForOtaUpdate: bindPublicMethod("checkForOtaUpdate"),
  getReleaseChangelogs,
  startOtaUpdate,
  queryOtaStatus,
  startAr99OtaFromFile: bindPublicMethod("startAr99OtaFromFile"),
  cancelAr99Ota: bindPublicMethod("cancelAr99Ota"),
  sendAr99FactoryReset: bindPublicMethod("sendAr99FactoryReset"),
  buildAr99OtaSignature: bindPublicMethod("buildAr99OtaSignature"),
  setSttModelDetails: bindPublicMethod("setSttModelDetails"),
  getSttModelPath: bindPublicMethod("getSttModelPath"),
  checkSttModelAvailable: bindPublicMethod("checkSttModelAvailable"),
  validateSttModel: bindPublicMethod("validateSttModel"),
  extractTarBz2: bindPublicMethod("extractTarBz2"),
  restartTranscriber: bindPublicMethod("restartTranscriber"),
  setTtsModelDetails: bindPublicMethod("setTtsModelDetails"),
  getTtsModelPath: bindPublicMethod("getTtsModelPath"),
  getTtsModelLanguage: bindPublicMethod("getTtsModelLanguage"),
  checkTtsModelAvailable: bindPublicMethod("checkTtsModelAvailable"),
  validateTtsModel: bindPublicMethod("validateTtsModel"),
  generateTtsAudio: bindPublicMethod("generateTtsAudio"),
})

export default BluetoothSdk

export {
  CAMERA_FOV_DEFAULT,
  CAMERA_FOV_MAX,
  CAMERA_FOV_MIN,
  DeviceModels,
  isBusyGlassesConnectionStatus,
  isConnectedGlassesConnectionStatus,
  isConnectedWifiStatus,
  isEnabledHotspotStatus,
  isReadyGlassesConnectionStatus,
} from "./BluetoothSdk.types"

export type {
  AccelEvent,
  Ar99OtaStatusEvent,
  AudioConnectedEvent,
  AudioDisconnectedEvent,
  AudioPairingNeededEvent,
  BatteryStatusEvent,
  BluetoothSdkEvent,
  BluetoothSdkEventListener,
  BluetoothSdkEventMap,
  BluetoothSdkEventName,
  BluetoothSdkPublicModule as BluetoothSdkModule,
  BluetoothSdkSubscription,
  ButtonPhotoSize,
  PhotoCaptureDefaults,
  ButtonPressEvent,
  CameraFovPreset,
  CameraFovRequest,
  CameraFovResult,
  CameraPreviewFormat,
  CameraPreviewStartParams,
  CameraPreviewStatusEvent,
  CameraPreviewStopReason,
  CameraRoiPosition,
  CompatibleGlassesSearchStopEvent,
  ConnectOptions,
  ConnectedGlassesConnectionStatus,
  ConnectedWifiStatus,
  Device,
  DeviceModel,
  EnabledHotspotStatus,
  GalleryStatusEvent,
  GlassesConnectionStatus,
  GlassesMediaVolumeGetResult,
  GlassesMediaVolumeSetResult,
  GlassesNotReadyEvent,
  HeadUpEvent,
  HotspotErrorEvent,
  HotspotStatus,
  HotspotStatusChangeEvent,
  GlassesSessionChangedEvent,
  KeepAliveAckEvent,
  LocalTranscriptionEvent,
  LogEvent,
  MicLc3Event,
  MicHealthEvent,
  MicMode,
  MicPcmEvent,
  MicPreference,
  OtaStartAckEvent,
  OtaProgress,
  OtaProgressStatus,
  OtaStage,
  OtaStatus,
  OtaStatusEvent,
  OtaQueryResult,
  OtaUpdateInfo,
  ReleaseChangelog,
  MtkUpdateCompleteEvent,
  PairFailureEvent,
  PairingInfoEvent,
  EnteringPairingModeEvent,
  OwnerReplacedEvent,
  PhotoCaptureMetadata,
  PhotoResolvedConfig,
  PhotoCompression,
  PhotoFpsRange,
  PhotoMeteredPreview,
  PhotoMode,
  PublicBluetoothStatus,
  PublicGlassesStatus,
  PhotoTransferMethod,
  PhotoResponseEvent,
  PhotoRequestedCaptureConfig,
  PhotoRequestParams,
  PhotoSize,
  PhotoStatusEvent,
  PhotoStatusState,
  PhotoSuccessResponseEvent,
  RgbLedAction,
  RgbLedColor,
  RgbLedControlResponseEvent,
  RgbLedControlSuccessResponseEvent,
  ScanModelOptions,
  ScanOptions,
  ScanResultsCallback,
  SpeakingStatusEvent,
  SettingsAckEvent,
  SettingsAckSetting,
  SettingsAckSuccessEvent,
  SettingsAckSuccessStatus,
  SettingsAckStatus,
  StreamAudioConfig,
  StreamResolvedConfig,
  StreamStartRequest,
  StreamStatusEvent,
  StreamStatusLifecycleState,
  StreamStatusReconnectState,
  StreamStatusState,
  StreamVideoConfig,
  SwipeVolumeStatusEvent,
  SwitchStatusEvent,
  TouchEvent,
  VideoRecordingDefaults,
  VideoRecordingStartedStatusEvent,
  VideoRecordingStatusEvent,
  VideoRecordingStatusState,
  VideoRecordingStoppedStatusEvent,
  VideoRecordingSuccessStatusEvent,
  VersionInfoEvent,
  VersionInfoResult,
  WifiScanResultEvent,
  VoiceActivityDetectionStatusEvent,
  WifiSearchResult,
  WifiStatus,
  WifiStatusChangeEvent,
} from "./BluetoothSdk.types"
